services:
  - type: web
    name: blogspace-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-sweet-resonance-b4zz7w7f-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_TSXiq3Es4PMZ
      - key: APP_JWT_SECRET
        value: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
